### ISSUE TITLE
Rename "Helping Those in Need" Page about Alaska

### ISSUE THREAD

**Issue by jposi** [18F/Modular-Contracting-And-Agile-Development#29]
"Helping those in Need" doesn't quite speak to the magnitude of the work, and  doesn't quite say what the thing is. Gonna do some brainstorming on what else might be a more specific option.

**Comment by mheadd** [comment]
Agreed - would love thoughts on another title for that page.

**Comment by mheadd** [comment]
This was changed via [this commit](https://github.com/18F/Modular-Contracting-And-Agile-Development/commit/652bfe019b7a67115d5f85e439c3c01dcfb4add9).
