### ISSUE TITLE
Expand section on 18Fs Agile BPA

### ISSUE THREAD

**Issue by zacharycohn** [18F/Modular-Contracting-And-Agile-Development#7]
From @mheadd: 

It might make sense to enhance the answer to the [question on using 18Fs Agile BPA](https://pages.18f.gov/state-faq/common-questions/#can-i-just-buy-off-18fs-agile-blanket-purchase-agreement-bpa).  Possible options for states that are interested in doing this are:

* [Using Schedule 70](http://www.gsa.gov/portal/content/141511) to contract directly with a vendor that is on our Agile BPA list.
* Developing their own agile vendor pool (with 18F assistance), like CA and MS have done.
* Creating a partnership with another state (CA, MS) and using a vendor from that state's existing agile vendor pool.

/cc: @MCHopson

**Comment by rrefoy** [comment]
Can probably close this for now. Hannah is going to start working on the 10x project for what's next after the agile bpa. perhaps some of that money can go into creating a page on this website explaining our best practices. what do you think @mheadd?

**Comment by mheadd** [comment]
Yeah, that makes sense. I also think this could fall under the work called for in #34.
